### ISSUE TITLE
关于V8 是否产生字节码

### ISSUE THREAD

**Issue by Yaxian** [Troland/how-javascript-works#5]
你好，

谢谢翻译！

我在第一章和第二章读到关于V8 引擎不产生字节码的内容。但是我在其他文章中，发现其他作者提到 V8引擎为了解决内存占用大和提高代码启动速度，V8 引擎又引入了字节码。

**Ignition, the interpreter, generates bytecode from this syntax tree. TurboFan, the optimizing compiler, eventually takes the bytecode and generates optimized machine code from it.**

这是文章链接 
* [V8 Ignition：JS 引擎与字节码的不解之缘](https://zhuanlan.zhihu.com/p/26669846) 
* [理解 V8 的字节码「译」](https://zhuanlan.zhihu.com/p/28590489)
* [Understanding V8’s Bytecode](https://medium.com/dailyjs/understanding-v8s-bytecode-317d46c94775)

请问，需要更正文档里的描述吗？

**Comment by Troland** [comment]
非常感谢您的阅读，是这样的这里文章所说的不产生字节码是对于 V8 **v5.9** 版本之前即当在使用 full-codegen 的时候，那么在 V8 **v5.9** 出现之后就有通过 TurboFan 把 Ignition 字节码转换为优化后的机器码，这样就可以有效地降低内存使用率，可细看[官方博客](https://v8.dev/blog/launching-ignition-and-turbofan)。
