### ISSUE TITLE
第四章有误

### ISSUE THREAD

**Issue by Machiavellid** [Troland/how-javascript-works#9]
![image](https://user-images.githubusercontent.com/42051023/126606566-05f07e83-a6cf-4ef5-8807-2800a55c4162.png)
 此处应当是5毫秒

**Comment by Troland** [comment]
非常感谢你的参与，那么，原文是这么写的，然后，再参考一下 eventloop 官方文档，即可知，一次 eventloop 只能处理一次任务，setTimeout 是属于一个任务，它必须要等待当前的 task 及 microTask 执行完毕才可以执行，比如，当前页面有涉及到复杂的运算，那么，当前线程便会阻塞，而 setTimeout 必须要等待，即可能会出现超过五秒才将回调压入回调队列。

仔细，想一下，画一下流程图，是不是这么回事？欢迎提意见，共同进步，谢谢，-.-。

**Comment by Troland** [comment]
@Machiavellid 相关文档 [eventloop](https://html.spec.whatwg.org/multipage/webappapis.html#event-loops)
